### ISSUE TITLE
How does this plugin work in intellij?

### ISSUE THREAD

**Issue by dinbtechit** [JTSchwartz/SmartSort#3]
How does this plugin work in intellij? It would be very helpful if you can add some readme and docs. Cheers

**Comment by JTSchwartz** [comment]
As this is an IntelliJ plugin, all documentation can be found on the JetBrains Plugin Repository (a link to which can be found in the About section of this repo). All information there is pulled from `resources/META-INF/plugin.xml`, making a README a redundant file to maintain within the code. I apologize for any inconvenience but ask that you find everything you need there so as to reduce the chance of out-of-sync documentation

**Comment by dinbtechit** [comment]
I agree doesn't make sense to maintain 2 separate documentation. But it would help if there were some screenshots! Honestly it's not clear how to even run the sorting?!  From context menu or in Menu -> Code. Where is the smartSort option? 

![image](https://user-images.githubusercontent.com/17984781/134783875-63fbef9d-7a1c-4c48-bffb-c24c80b5a6c8.png)

**Comment by JTSchwartz** [comment]
I will be sure to add this information in an upcoming release. I had incorrectly assumed that becayse IntelliJ comes with a simple Sort functionality within the Edit menu that users would inherently look there.
